base: &common
  site: <%= ENV["PUBLIC+URL"] %>
  analytics_id: UA-10385211-1
  analytics_vendor: googlean
  session_key: _shapado_session
  session_secret: <% Digest::SHA1.hexdigest(ENV["BUSHIDO_SALT"])
  rest_auth_key: b4d66d73a1ade79ce227fba01b33f2ab021888ef
  rest_auth_digest_stretches: 10
  enable_sharing: true
  notification_email: notifications@example.com
  default_language: en
  adbard_host_id: 2746b6d24c93f71df12503ec2ab667e5
  adbard_site_key: e8e24a6b2cba51145dc0c874e1b2f4a4
  enable_adbard: false
  application_name: <% ENV["SHAPADO_APP_NAME"] || ENV["BUSHIDO_NAME"] %>
  is_shapadocom: false
  enable_groups: false
  default_language: en
  enable_i18n: false
  default_timezone: "Tokyo"

  smtp:
    activate: true
    server: <%= ENV["SMTP_SERVER"] %>
    port: <%= ENV["SMTP_PORT"] %>
    domain: <%= ENV["SMTP_DOMAIN"] %>
    login: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>

  facebook:
    activate: false
    key: facebook api key
    secret: facebook secret key

  twitter:
    activate: false
    key: twitter api key
    secret: twitter secret key

  recaptcha:
    activate: true
    public_key: your public key
    private_key: your private key

  exception_notification:
    activate: true
    exception_sender_address:
      "[Shapado] error notifier <error-notifier@example.com>"
    exception_recipients:
    - admin@example.com

development:
  <<: *common
  domain: localhost.lan
production:
  <<: *common
  domain: <%= ENV["BUSHIDO_DOMAIN"] %>
  googlean_domain: .shapado.com
test:
  <<: *common
  domain: test.loc

